# Generated by Django 5.0.2 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_planet_color'), ('app', '0003_planet_count')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('satellite', models.CharField(max_length=255)),
                ('color', models.CharField(default=1, max_length=255)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
