# Generated by Django 5.0.2 on 2024-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='color',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
